### ISSUE TITLE
Targets > Look up an Instance shows no data

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#421] opened 2015-08-13 11:48 UTC

**Comment by anjackson** [comment] 2015-08-13 14:37
Actually, lets push this back to the next version, as instances are not heavily used yet and we could use some feedback about how they should work.

**Comment by ldbiz** [comment] 2016-03-10 11:43
I am unable to reproduce this, perhaps it has been fixed or was a data issue? Instance lookups do return data now, however they have the slight drawback of killing the entire application, for which I've raised a new issue #500.

**Comment by GilHoggarth** [comment] 2016-06-28 11:15
Closed as issue undocumented.

**Closed by GilHoggarth** 2016-06-28 11:15 UTC
Labels: 1 - Ready to test on stage, Bug, Question
