### ISSUE TITLE
Professional Judgement check box under NPLD Scope cannot be unset

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#424] opened 2015-08-13 14:26 UTC

**Comment by anjackson** [comment] 2015-08-13 14:28
It can't be unset if the Judgement explanation field is filled, by design. Or is that empty too?

**Comment by niladreeb** [comment] 2015-08-13 14:29
When the explanation field is empty and check box unchecked, then after saving the view shows it is still checked.

**Comment by anjackson** [comment] 2015-08-13 14:34
Fixed now - BTW we're still building up to 1.1.0 release proper, so we don;t need to push this on to 1.2.0.

**Comment by niladreeb** [comment] 2015-08-14 13:33
Tested on actstage and it works fine.

**Comment by niladreeb** [comment] 2015-08-17 13:42
Retested and acts fine.

**Comment by GilHoggarth** [comment] 2015-09-02 13:19
Nils, please test this ticket.

**Comment by niladreeb** [comment] 2015-09-02 13:26
Working fine in actstage.

**Comment by GilHoggarth** [comment] 2015-09-09 09:10
Me, test - consider roles?

**Comment by GilHoggarth** [comment] 2015-09-09 10:22
Tested and working on /actstage.

**Comment by GilHoggarth** [comment] 2015-09-10 10:34
Seen to be possible now.

**Closed by GilHoggarth** 2015-09-10 10:34 UTC
Labels: 3 - Done, bug
