### ISSUE TITLE
Adding licences manually in ACT is not working

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#566] opened 2017-02-08 14:42 UTC
I think this is related to #565 or possibly is the same issue. I tried to change the status of the Target to "Granted" by selecting the licence type 'Joint LDL Web Archiving Licence (2016-)' and selecting 'Granted'. When hitting save the Licence Status changes (correctly) to Granted but the UKWA Licencing tab changes to (~) (Pending), whereas it should be (+). 
We're not seeing the Granted status reflected in the whitelisting for open access so I don't think the Licence Status field is working. Could you investigate please? 
![licence_type](https://cloud.githubusercontent.com/assets/11210500/22741883/adb03a5c-ee0c-11e6-8c19-a07c5c34a8bc.png)

**Comment by anjackson** [comment] 2017-03-21 16:09
Resolved by #573 - please re-open this issue if the problem is note resolved by the 2.0.6 release.

**Closed by anjackson** 2017-03-21 16:09 UTC
Labels: 1 - Not working, Bug, Medium Priority
