### ISSUE TITLE
Add covering letter and acknowledgement emails to ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#513] opened 2016-05-19 12:38 UTC
On another ticket, #474, we have requested an enhancement which will allow Archivists to create different covering letters for the different types of permission that we send out. These are sent to publishers in an email introducing web archiving and containing a link to the licence form. 

Different letters are needed for the different agencies using ACT (BL, NLS, NLW etc.) and for different situations e.g. requesting permission to *harvest* for non-NPLD content as well as requesting permission for open access to content harvested under NPLD. 

While we wait for the implementation of #474 in a future production release, can we add the following emails to ACT on the Mail Templates page please https://www.webarchive.org.uk/act/mailtemplates (Archivists Tasks > Mail Templates).  

The title of the templates (to be displayed on the Mail Templates page):

**BL Acknowledgement**
Text of the email in: 1_BL.acknowledgement.txt

**NLS Acknowledgement**
Text of the email in: 2_NLS_acknowledgement.txt

**NLW Acknowledgement**
Text of the email in: 7_NLW_acknowledgement.txt 

**BL Open Access Permission Request (LD Content)**
3_BL_LD_openAccess.txt

**NLS Open Access Permission Request (LD Content)**
4_NLS_LD_openAccess.txt

**NLW Open Access Permission Request (LD Content)**
8_NLW_LD_openAccess.txt

**NLW_LD_openAccess_WELSH.txt**
NLWCovering letter Welsh Translation.docx

**BL Permission to Harvest (non NPLD Content)**
5_BL_nonUK_nonLD.txt

**NLS Permission to Harvest (non NPLD Content)**
6_NLS_nonUK_nonLD.txt

**NLW Permission to Harvest (non NPLD Content)**
9_NLW_nonUK_nonLD.txt 

[7_NLW_acknowledgement.txt](https://github.com/ukwa/w3act/files/293575/7_NLW_acknowledgement.txt)
[8_NLW_LD_openAccess.txt](https://github.com/ukwa/w3act/files/293576/8_NLW_LD_openAccess.txt)
[9_NLW_nonUK_nonLD.txt](https://github.com/ukwa/w3act/files/293577/9_NLW_nonUK_nonLD.txt)
[5_BL_nonUK_nonLD.txt](https://github.com/ukwa/w3act/files/272564/5_BL_nonUK_nonLD.txt)
[2_NLS_acknowledgement.txt](https://github.com/ukwa/w3act/files/272563/2_NLS_acknowledgement.txt)
[4_NLS_LD_openAccess.txt](https://github.com/ukwa/w3act/files/272565/4_NLS_LD_openAccess.txt)
[6_NLS_nonUK_nonLD.txt](https://github.com/ukwa/w3act/files/272562/6_NLS_nonUK_nonLD.txt)
[1_BL_acknowledgement.txt](https://github.com/ukwa/w3act/files/272561/1_BL_acknowledgement.txt)
[3_BL_LD_openAccess.txt](https://github.com/ukwa/w3act/files/272566/3_BL_LD_openAccess.txt)
[NLWCovering letter Welsh Translation.docx](https://github.com/ukwa/w3act/files/293595/NLWCovering.letter.Welsh.Translation.docx)

**Comment by anjackson** [comment] 2016-05-19 13:46
I think most of this is DB additions once the files are deployed, alongside the others here: https://github.com/ukwa/w3act/tree/master/conf/templates

@chrispeacockbl and/or @ldbiz can you confirm and add them in?

**Comment by GilHoggarth** [comment] 2016-06-27 13:57
Roll out of these new mail templates, understood to be added via 4.sql, incomplete. The current state can be seen on https://www.webarchive.org.uk/actstage/mailtemplates does not match the number of templates stated above.

@chrispeacockbl , can you check this please - are the other templates missing or has the deployment failed?

**Comment by chrispeacockbl** [comment] 2016-06-28 14:17
@GilHoggarth Please could you redeploy this and test again.

**Comment by GilHoggarth** [comment] 2016-06-28 15:08
@chrispeacockbl Redeployed, still no mention of NLW. Is there an update necessary for the database, as opposed to just the W3ACT code, that needs to be run?

**Comment by chrispeacockbl** [comment] 2016-06-28 15:09
@GilHoggarth Yes - I added the needs-db-changes label!

**Comment by GilHoggarth** [comment] 2016-06-28 15:21
So what needs to be done for these database changes? Such actions should be defined in evolutions SQL so can include/exclude when releasing new/previous versions of code.
If the necessary change doesn't easily fit into evolutions then the necessary action should be declared in the ticket.

**Comment by chrispeacockbl** [comment] 2016-06-28 15:24
Yes, it is in the evolutions - there is an update to the 4.sql file, checked in along with my other changes today.

**Comment by GilHoggarth** [comment] 2016-06-28 15:25
Ah I know, the evolutions stuff is disabled by default, for safety reasons I think. I'll enable it and restart...

**Comment by chrispeacockbl** [comment] 2016-06-28 15:27
OK - I was just about to say "but they still haven't appeared?"!

**Comment by GilHoggarth** [comment] 2016-06-28 15:28
"But they still haven't appeared." I'll look into the database to see if the sql completed successfully.

**Comment by GilHoggarth** [comment] 2016-06-28 15:30
Arse.

**Comment by chrispeacockbl** [comment] 2016-06-28 15:30
I was just going to say "Can I swear on here?"

**Comment by GilHoggarth** [comment] 2016-06-28 15:31
No.

**Comment by chrispeacockbl** [comment] 2016-06-28 15:33
:-(
Still no new records?

**Comment by GilHoggarth** [comment] 2016-06-28 15:34
When updating services it's quite important to update the right service.

**Comment by chrispeacockbl** [comment] 2016-06-28 15:36
Unless you're updating unimportant services, surrounded by other unimportant services.

**Comment by GilHoggarth** [comment] 2016-06-28 15:41
I haven't communicated this with you or Lee but in the labels have some vague structure/meaning.
Those starting with a number are meant to highlight the stage of development/testing/roll out. Thus, just trying to be clear, "2 - Data change required" should be used when the database has to be updated.

'needs-db-changes' should be renamed really but it's typically used to highlight that the issue will require changes to the database before the issue is completed. I.e., it's trying to pass information to the developer.

We need to go through our release process in better detail, which we should do when Andy's back.

**Comment by chrispeacockbl** [comment] 2016-06-28 15:43
Sorry, I think you might have mentioned that before. I did wonder whether to remove that "1 - Not working" when I added the "...Ready to test" label earlier.

**Comment by GilHoggarth** [comment] 2016-06-28 15:44
And now all the mail templates appear. Assigned to @nicolabingham to check the implementation works for the curators.

**Comment by chrispeacockbl** [comment] 2016-06-28 15:45
Great, thanks.

**Comment by GilHoggarth** [comment] 2016-06-30 12:33
Seen on live, closing.

**Closed by GilHoggarth** 2016-06-30 12:33 UTC
Labels: 2 - Data change required, 3 - Done, Enhancement, High Priority
