### ISSUE TITLE
Search URL problems

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#463] opened 2015-11-10 10:08 UTC
In the last few days I've had problems with the search function. It's not always working for the URL, but seems to work with the titles. The URLs https://sites.google.com/site/thimbleidentificatio/ and https://sites.google.com/site/mujb195658/ have been added to ACT, but when searching for them, the result is 0. It works ok for the 'Manchester University Jazz Band' and 'Thimble identification'.

**Comment by ldbiz** [comment] 2016-03-09 15:06
Unable to reproduce using the above and other examples. Assuming it wasn't a temporary data/indexing issue, there have been changes to the Target search functionality (eg. #473), so I suggest this may not still be a problem. 

Perhaps this can be revisited and closed?

**Comment by anjackson** [comment] 2016-03-11 10:55
I think changing the URL search logic fixed this.

**Comment by GilHoggarth** [comment] 2016-06-28 10:56
Tested on production /act, seems to now be working. Closing issue.

**Closed by GilHoggarth** 2016-06-28 10:56 UTC
Labels: 1 - Ready to test on stage, Question
