### ISSUE TITLE
sorting curators by role shows an SQLException

### ISSUE THREAD

**Issue by romankarl** [ukwa/w3act#322] opened 2015-03-25 14:10 UTC
If you try to sort curators by role you get an SQLException.

http://www.webarchive.org.uk/actdev/curators/list?s=roles

So either the sorting should be fixed or the sorting link should be removed.

**Comment by GilHoggarth** [comment] 2015-03-25 14:11
Assigning to Andy for inclusion in appropriate milestone.

**Comment by anjackson** [comment] 2015-05-21 22:42
Cannot reproduce this. Has it been fixed, @romankarl?

**Comment by romankarl** [comment] 2015-05-22 06:39
Yes, it has beed fixed the same day I reported it (8ce781cee36c74baa3047f620b6b0dd08b38efe2).

**Closed** 2015-05-22 06:40 UTC
Labels: bug
