### ISSUE TITLE
Unable to assign licence type in ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#565] opened 2017-01-26 09:22 UTC
We are unable to assign the licence 'HLF WW1 Agreement' to this target https://www.webarchive.org.uk/act/targets/48574. For Targets with licences granted outside of the system we should be able to update the Target record manually.

**Comment by anjackson** [comment] 2017-01-26 09:56
What happens when you try to do it? An error? Or does it just not change the licence?

**Comment by nicolabingham** [comment] 2017-01-26 09:57
The latter; there is no change in the record.

**Comment by ldbiz** [comment] 2017-03-06 16:20
One observation @chrispeacockbl and @min2ha noted last week was that in different browsers the selection list (with the licenses) can have its sensitivity (whether it is disabled or not) represented slightly differently. Apparently in some instances it is still selectable, but grayed out. This could explain why a save didn't occur.

Presumably this isn't the case, but we could do with ruling it out, @min2ha is going to check this with @nicolabingham then update this issue so we can try and reproduce as currently described (License is selectable, but nor persisted on Save).

**Comment by min2ha** [comment] 2017-03-09 15:56
Just quick update, 
according to issue 565, I need database dump, where status is **Queued**, not **Granted**, for **TARGET ID = 48574**.

`SELECT license_status
  FROM public.target where id=48574;`

at the moment the dump of live system database (which I have) is showing that **license_status** of **target id=48574** is **GRANTED**

Lee is helping me to get the right version of dump file of live system database, in order to reproduce issue on my local machine.

**Comment by min2ha** [comment] 2017-03-20 10:55
Back to bugfix. Sorry, I need some comments on permission rights for targets.
So, we have organisation "The British Library", where we have many curators assigned to it. 
Is it possible that **some other curator from same organisation could change other curator's who owns some target settings**? 
@nicolabingham wrote "We are unable to assign the licence 'HLF WW1 Agreement' to this target" (i.e.48574). 
I see that target 48574 is owned by "Helena Byrne". 
Could @nicolabingham explain who were **"We"**, who were unable to assign the licence?
Maybe "Helena Byrne" could assign the licence only, because of being owner?
Thanks for comments in advance.

**Comment by nicolabingham** [comment] 2017-03-20 10:57
@min2ha Hi. "We" refers to both myself and Helena. Neither one of us was able to manually assign the HLF WW1 Agreement to the Target. Both of us *should* be able to do this as we have the Archivist role in the system.

**Comment by min2ha** [comment] 2017-03-21 09:25
Hi everybody, hopefully trivial small change in targets/edit.scala.html file fixed this #565 and #566 bugs.
The problem was that **archivist role** was not included in the manual licensing, that's why **licensesList** was disabled for everybody except **sys_admin**.
Anyway I will need assistance to test it the proper way.

**Comment by nicolabingham** [comment] 2017-03-21 09:27
@min2ha Brilliant! Helena and myself would be very happy to test this. @anjackson when can we deploy the fix to the live system (assuming it's not already live)

**Comment by anjackson** [comment] 2017-03-21 10:52
I've not seen the patch yet (feel free to push this to github @min2ha !) but if it's as small as it sounds we can just roll a point release and release it straight away.

**Comment by anjackson** [comment] 2017-03-21 16:09
Resolved by #573 - please re-open this issue if the problem is note resolved by the 2.0.6 release.

**Closed by anjackson** 2017-03-21 16:09 UTC
Labels: Bug, Medium Priority
