### ISSUE TITLE
Save button does not always work

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#460] opened 2015-10-26 14:20 UTC
Recently I've noticed there are some problems with saving a target record. It doesn't always happen and normally clicking between the tabs helps. It's occured for new and edited targets. It affects only the 'save' button at the top, the one at the bottom of the page seems ok.

**Comment by chrispeacockbl** [comment] 2016-05-12 15:10
I could not reproduce this, in several browsers, however I noticed that the IDs of the buttons in the edit section were not unique, which can cause problems. I've corrected this.

**Comment by GilHoggarth** [comment] 2016-06-28 10:57
This is another deep issue that may only be regarded as fixed but observing if the problem occurs again. Consequently closing issue.

**Closed by GilHoggarth** 2016-06-28 10:57 UTC
Labels: Medium Priority
