### ISSUE TITLE
Date Granted not sorting properly

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#468] opened 2015-11-20 13:02 UTC
In the Archivist tasks -> Crawl permissions -> filter by status 'Granted' the sorting function 'Granted Date' is not working properly as the dates are not in descending order (they were before the 1.1.2 deployment). I'm not sure about the ascending order as the data is not available for earlier targets. The same problem occurs for the 'Requested Date' sorting.

**Comment by anjackson** [comment] 2015-11-20 13:35
Just to check I'm not missing anything - i think this is sorted by ascending Granted Date

https://www.webarchive.org.uk/act/crawlpermissions/list?s=grantedAt&status=GRANTED

And this is sorted by ascending Requested Date

https://www.webarchive.org.uk/act/crawlpermissions/list?s=requestedAt&status=GRANTED

But the issue is that you need the other order to work, and in descending order the 'blanks' come first and so you have to go to the page 10 to see the results:

https://www.webarchive.org.uk/act/crawlpermissions/list?p=10&s=grantedAt&o=desc&status=GRANTED

i.e. the permissions with no dates need to be at the end of the list no-matter what the sorting order is.

**Comment by ldbiz** [comment] 2016-03-18 14:29
I've spent some time trying to get this working with our framework, but it doesn't seem do-able using the obvious options.

Unfortunately, subject to this being revisited, the user will need to restrict the number of results to make it more manageable.

Developer note:

I've tried:
the Ebean.sort method which caters for NullsHigh and NullsLow - I couldn't get it to work at all
and
converting a standard SQL ORDER BY <date> IS NULL, <date> which works fine in Postgres, but exceeds the complexity of Ebeans orderBy clause.

It will be worth fresh eyes on the above, but if it cannot be done, the alternative is RawSQL, which may be too heavy a fix for this issue.

**Comment by anjackson** [comment] 2016-03-18 15:45
Okay, this looks difficult, so an alternative is simply to omit the ones with no date when sorting on that field. I'll add a commit to try this.

**Comment by ldbiz** [comment] 2016-04-28 09:38
Testing note: Following @anjackson's changes, to see all the rows again (unsorted), click search.

**Comment by GilHoggarth** [comment] 2016-06-28 10:49
Seen working on /act, ie production. C'est la vie, closing.

**Closed by GilHoggarth** 2016-06-28 10:49 UTC
Labels: 2 - Tested and working on stage, Bug, Low Priority
